### PR TITLE
Bump requests >= 2.21.0, <= 2.24.0 and simple_json >= 3.16.0, <= 3.17.2

### LINKED ISSUE #64: Requests library upgrade
Hi all, 

is there any reason or incompatibility issue for not upgrading `requests` library's version? It would be great if the shippo client could allow it to work with its latest version (`2.24.0`). 

I can't imagine there is any breaking changes or issues coming from that!

### PR DESCRIPTION
**Pull request by TysonRV**
- Increase range for `requests` and `simple_json` libraries, as right now it supports just one version of each and this tends to cause incompatibilities with other libraries.

Testing this with different `requests` and `simple_json` versions was satisfactory.

Fixes #64

### CODE REVIEW

**Comment by TysonRV** [comment]
Builds seem to be missing a valid API key... I can see they have been failing for a while now

**Comment by nickbaum** [comment]
As of today, **Shippo's Python library is incompatible with Amazon's boto library** that is used for accessing all of AWS.
* Shippo hardcodes requests 2.21
* Requests 2.21 requires urllib3 <= 1.25
* Boto requires urllib3 >=1.25.4

**This would be solved by merging this PR.**

More broadly, there's a tension between minimizing breakage:
* due to breaking changes in minor version releases
* due to dependency incompatibilities with other libraries

Certainly for a well-maintained library like requests, I'd recommend erring towards a more lenient version specification until/unless you've experienced actual issues with minor upgrades.

PS: Thanks @TysonRV for the PR!

**Comment by jfriedr** [comment]
Thanks for the PR!

@TysonRV If you could please redact the inclusions of the `.gitignore` file as well as the removal of the unused imports. Once that's changed I'd be happy to get this included and pushed to pypi later today.

@nickbaum thanks for elaborating.

**Comment by TysonRV** [comment]
@jfriedr That's no problem, I'll just drop the commits. Can I ask what's the motivation behind getting rid of those changes? Is it to keep the PR as clean as possible?

Thanks!

**Comment by nickbaum** [comment]
Haha, @TysonRV, you beat me to it!

**Comment by TysonRV** [comment]
@nickbaum Oh, didn't even see it sorry! 😅

**Review by jfriedr — APPROVED** [review]
:+1: looks good

**Comment by jfriedr** [comment]
@TysonRV @nickbaum I've pushed the update to pypi.  Thanks again for the pull request(s) and context surrounding the dependencies.  

https://pypi.org/project/shippo/#history

**Comment by nickbaum** [comment]
🎉 Thanks to all for getting this resolved!

**Pull request merged**
