### PR TITLE
Increase requests requirements range

### PR DESCRIPTION
**Pull request by jfriedr**
New version of requests released on 13 Jul, 2021

image

### CODE REVIEW

**Comment by epistemancer** [comment]
Guess we don't have CI configured to run tests for this repo, but tests passed locally for me with requests==2.26.0 and urllib3==1.26.6.

**Review by epistemancer — APPROVED** [review]

**Comment by nickbaum** [comment]
I see this was merged. Any timeline for when it might be released?

(requests 2.24 causes a dependabot alert on github)

**Comment by jfriedr** [comment]
We're in the process of reviewing an addition that adds orders within the week and this change will be included in that release.  Thanks for bumping the thread, apologies it was not published sooner.

**Comment by nickbaum** [comment]
Happy New Year! Any chance you can do a very minor release with just this fix, since it triggers Github's dependabot alerts?

**Comment by jfriedr** [comment]
@nickbaum this was bumped.  I can't apologize enough for the delay.  Please let me know if something else comes up.

**Comment by nickbaum** [comment]
@jfriedr Thanks so much for tackling this 🙏🏻

**Pull request merged**
